fix(cli): doom upgrade: reformat & revise output/errors
Display helpful errors for new edge case: where $EMACSDIR is not the
root of the git repo.

And tidy up error message if modifications are detected.

Before:
  > Preparing to upgrade Doom Emacs and its packages...
  Error: (Refusing to upgrade because "~/projects/config/emacs.d/" has been modified.

  Either stash/undo your changes or run 'doom upgrade --force' to discard local changes.

    M README.md
   M shell.nix)

  Aborting...

After:
  x Refusing to upgrade because Doom contains modifications!
    Either stash/undo your changes or run 'doom upgrade --force' to
    discard local changes:

     M README.md
     M bin/doom-upgrade
     M lisp/doom-cli.el
     M shell.nix